# Generated by Django 3.2.12 on 2022-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('device_timestamp', models.DateTimeField()),
                ('recording_type', models.IntegerField()),
                ('glucose_value_history', models.IntegerField()),
                ('glucose_scan', models.IntegerField()),
                ('rapid_acting_insulin', models.CharField(max_length=100)),
                ('rapid_insulin', models.IntegerField()),
                ('nutritional_data', models.CharField(max_length=100)),
                ('carbohydrates_gram', models.IntegerField()),
                ('carbohydrates_servings', models.IntegerField()),
                ('depot_insulin', models.CharField(max_length=100)),
                ('depot_insulin_units', models.IntegerField()),
                ('notes', models.CharField(max_length=100)),
                ('glucose_test_strips', models.IntegerField()),
                ('ketone', models.IntegerField()),
                ('meal_insulin', models.IntegerField()),
                ('correction_insulin', models.IntegerField()),
                ('user_insulin_change', models.IntegerField()),
            ],
        ),
    ]
