# Generated by Django 3.2.12 on 2022-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosedata',
            name='carbohydrates_gram',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='carbohydrates_servings',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='correction_insulin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='depot_insulin_units',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='glucose_scan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='glucose_test_strips',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='glucose_value_history',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='ketone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='meal_insulin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='rapid_insulin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='recording_type',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucosedata',
            name='user_insulin_change',
            field=models.IntegerField(blank=True),
        ),
    ]
